---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-plus-prepare
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: policygenerator/policy-sets/community/openshift-plus-setup
    repoURL: https://github.com/ch-stark/policy-collection
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: false
      prune: true  
